import crypto from 'crypto';

const TRIAL_DAYS = 7;

// Embedded public key for license verification
// Generated by: node scripts/generate-license.js
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnBmaK18W4gBdh146CSZB
bPmCi5Uth70GTWSvMwmin86Z4J9XAbTBSrut81c4POpi5CUWst4H6OVRx6hltKap
kHh8tSr/3NgNrZyc3TBkhMSrGy5hPAUE/6pjXaNnwG1WCjeHrWwP812zlHe798f3
USZ+S4jnf1fHiSX64+HeZ4+I7wVP3U9k0zX28WLtb9LUScDAkhzaQobWFT5IVa+7
r+5mLhQb71nJNZJwMw55cIJ/m8Yct6m85uaV+fvu1klOYauUt5C49zaBS8Pa4DAk
4Z/KJk14x/dZ8zykxHFjB6tZzyshBLDwoI5w+uFQvUPeuJI8rnjt2NEBE1QG7KEM
LwIDAQAB
-----END PUBLIC KEY-----`;

function fromBase64Url(str) {
  let b64 = str.replace(/-/g, '+').replace(/_/g, '/');
  while (b64.length % 4) b64 += '=';
  return Buffer.from(b64, 'base64');
}

/**
 * Validate a license key string.
 * Format: <base64url-payload>.<base64url-signature>
 * @returns {{ valid: boolean, email?: string, type?: string, issuedAt?: string, expiresAt?: string, error?: string }}
 */
export function validateLicenseKey(keyString) {
  if (!keyString || typeof keyString !== 'string') {
    return { valid: false, error: 'No license key provided' };
  }

  const parts = keyString.trim().split('.');
  if (parts.length !== 2) {
    return { valid: false, error: 'Invalid license key format' };
  }

  const [payloadB64, signatureB64] = parts;

  try {
    const signature = fromBase64Url(signatureB64);
    const isValid = crypto.verify(
      'sha256',
      Buffer.from(payloadB64),
      PUBLIC_KEY,
      signature
    );

    if (!isValid) {
      return { valid: false, error: 'Invalid license key signature' };
    }

    const payload = JSON.parse(fromBase64Url(payloadB64).toString('utf-8'));

    if (payload.expiresAt && new Date(payload.expiresAt) < new Date()) {
      return { valid: false, error: 'License key has expired', email: payload.email };
    }

    return {
      valid: true,
      email: payload.email,
      type: payload.type,
      issuedAt: payload.issuedAt,
      expiresAt: payload.expiresAt || null
    };
  } catch {
    return { valid: false, error: 'Failed to verify license key' };
  }
}

/**
 * Initialize trial if not already started.
 * Call on every app launch.
 */
export function initTrial(config) {
  const info = config.getLicenseInfo();
  if (!info.trialStartDate) {
    config.setLicenseInfo({ ...info, trialStartDate: new Date().toISOString() });
  }
}

/**
 * Check if the trial period is still active.
 * @returns {{ active: boolean, daysRemaining: number }}
 */
export function isTrialActive(config) {
  const info = config.getLicenseInfo();
  if (!info.trialStartDate) {
    return { active: true, daysRemaining: TRIAL_DAYS };
  }

  const start = new Date(info.trialStartDate);
  const now = new Date();
  const elapsed = (now - start) / (1000 * 60 * 60 * 24);
  const remaining = Math.max(0, Math.ceil(TRIAL_DAYS - elapsed));

  return { active: remaining > 0, daysRemaining: remaining };
}

/**
 * Check if the stored license key is valid.
 */
export function isLicensed(config) {
  const info = config.getLicenseInfo();
  if (!info.key) return false;
  const result = validateLicenseKey(info.key);
  return result.valid;
}

/**
 * Get unified license status for UI display.
 */
export function getLicenseStatus(config) {
  const info = config.getLicenseInfo();

  // Check stored license first
  if (info.key) {
    const result = validateLicenseKey(info.key);
    if (result.valid) {
      return {
        licensed: true,
        trial: false,
        expired: false,
        daysRemaining: null,
        email: result.email,
        type: result.type,
        expiresAt: result.expiresAt
      };
    }
  }

  // Fall back to trial
  const trial = isTrialActive(config);
  return {
    licensed: false,
    trial: trial.active,
    expired: !trial.active,
    daysRemaining: trial.daysRemaining,
    email: null,
    type: null,
    expiresAt: null
  };
}

/**
 * Returns true if the app should be usable (licensed or in trial).
 */
export function isAppUsable(config) {
  return isLicensed(config) || isTrialActive(config).active;
}
